site_name: MARSH Documentation
site_url: https://marsh-sim.github.io/
repo_url: https://github.com/marsh-sim/marsh-sim.github.io
edit_uri: edit/main/docs/

site_description: Documentation for projects in MARSH-Sim research simulator
site_author: Marek S. Lukasiewicz
copyright: "Â© 2024, Marek S. Lukasiewicz, CC-BY 4.0"

nav:
  - Home: README.md
  - Manager:
    - MARSH Manager: manager/README.md
    - Development: manager/development.md
  - Nodes:
    - Simulator nodes: nodes/README.md
    - Instruments: nodes/instruments.md
    - Eye tracking: nodes/eye-tracking.md
    - Body pose: nodes/body-pose.md
    - Development: nodes/development.md
  - Data analysis:
    - MATLAB: analysis/matlab.md
  - MAVLink definitions:
    - Minimal Set: mavlink/minimal.md
    - Subset of Common Set: mavlink/common.md
    - MARSH Dialect: mavlink/marsh.md
  - Project:
    - Rationale: rationale.md
    - Documentation: documentation.md
    - Bibliography: bibliography.md

theme: readthedocs

extra_css:
  - external_links.css
  - mavlink_table.css

markdown_extensions:
  - admonition
